[build]
  command = "echo 'Running in development mode'"
  publish = "/*"

[dev]
  command = "echo 'Running in development mode'"

[build]
  command = "echo 'Running in development mode'"
  publish = "/"